### ISSUE TITLE
Test Basil guide end-to-end

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos-docs#13]
We wrote a guide in https://github.com/zeppelinos/zos-docs/blob/master/docs/docs/basil.md
However, the zos released version has some problems, so I haven't tested this end-to-end with the new release.

We need to make sure that a user can start from scratch and follow the entire guide without errors or confusions on the way.

**Comment by fiiiu** [comment]
Changed End-to-end to Basil Demo.

**Comment by roschler** [comment]
@fiiiu The version attached to the above post supersedes the changes I suggested on the other ZOS repo.  Right now I can't find the edits you suggested.  Later I will modify the completed revision I attached to the above post, to include the changes you suggested on that other repo, once the _onlyOwner_  failure I mentioned above is solved.

**Comment by dougiebuckets** [comment]
It was smooth sailing for me until I tried to link to the `openzeppelin-zos` standard release. When I run `zos push --from $OWNER --deploy-stdlib --network local` I get the following error:

```Successfully written zos.development.json

/usr/local/lib/node_modules/zos/node_modules/web3/lib/web3/errors.js:38
        return new Error(message);
               ^
Error: VM Exception while processing transaction: out of gas```
