### ISSUE TITLE
npx truffle compile failed

### ISSUE THREAD

**Issue by demibrener** [zeppelinos/zos-docs#43]
I'm strictly following the steps on https://docs.zeppelinos.org/docs/building.html and I get "Could not find suitable configuration file." when running "npx truffle compile". Maybe there's an extra step I should follow before running this command?

**Comment by fiiiu** [comment]
This was due to a missing `truffle.js` file. We are however adding functionality in `zos-cli` to get `zos init` to take care of truffle initialization.

**Comment by fiiiu** [comment]
Solved in https://github.com/zeppelinos/zos-cli/pull/202.
