### ISSUE TITLE
Fix links using the right URL protocol

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos-docs#69]
The API reference includes a link to the source of the contracts. For example, in:
https://docs.zeppelinos.org/docs/migrations_Initializable.html

This source link has this as the URL:
git+https://github.com/zeppelinos/zos-lib/blob/v0.1.12/contracts/migrations/Initializable.sol

The git+https is wrong, and can't be opened with the browser.

**Comment by facuspagnuolo** [comment]
Fixed with the new deploy
