### ISSUE TITLE
Add versioning to the reference section

### ISSUE THREAD

**Issue by fiiiu** [zeppelinos/zos-docs#78]
Docusaurus is able to handle different versions of a project, but we are not currently using this feature. Once we have more releases, it would be useful to have the reference section documentation reflect the different versions. The main hurdle with versioning is the syncing of the two repos: `zos-lib` and `zos-cli`. 

Before tackling this, we probably want to have fully automated the reference section generation (https://github.com/zeppelinos/zos-docs/issues/77).

**Comment by come-maiz** [comment]
This is already done: https://docs.zeppelinos.org/versions.html
