### ISSUE TITLE
zos upgrade MyContract --network local 

### ISSUE THREAD

**Issue by vitoc** [zeppelinos/zos-docs#90]
In https://docs.zeppelinos.org/docs/building.html (Building an upgradeable application), this is the command given to upgrade an application:

```
zos upgrade MyContract --network local
```

This command however is not available in version 1.1.0.

I believe the right command should be:

```
zos update MyContract --network local
```
<img width="741" alt="update" src="https://user-images.githubusercontent.com/558813/43149518-2aab31c6-8f9a-11e8-889c-371da341ded9.png">

**Comment by facuspagnuolo** [comment]
Thanks @vitoc! We just released a new update including a fix for this issue.
