### ISSUE TITLE
Update documentation and examples for multiple dependencies

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-docs#93]
Currently, we have two guides related to this new feature:
- [How to use a stdlib](https://docs.zeppelinos.org/docs/using.html)
- [How to develop a stdlib](https://docs.zeppelinos.org/docs/developing.html)

We will need to update both using the new terminology (TBD). We should also make explicit that we are now able to handle multiple deps.

**Comment by eternauta1337** [comment]
Addressed by https://github.com/zeppelinos/zos/pull/226
